version: '3'
services:
  # db
  auth-db:
    image: postgres:13-alpine
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${AUTH_DB_NAME}
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
    ports:
      - 5434:5432
  # redis
  auth-redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 30s
      timeout: 10s
      interval: 1s
      retries: 10
    volumes:
      - auth_redis_data:/data
  # api
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AUTH_DB_NAME=${AUTH_DB_NAME}
      - AUTH_DB_USER=${AUTH_DB_USER}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - AUTH_DB_HOST=${AUTH_DB_HOST}
      - AUTH_DB_PORT=${AUTH_DB_PORT}
      - AUTH_REDIS_PORT=${AUTH_REDIS_PORT}
      - AUTH_REDIS_HOST=${AUTH_REDIS_HOST}
      - PROJECT_NAME=${PROJECT_NAME}

volumes:
  # auth-db
  auth-db-data:
  # auth_redis
  auth_redis_data:
