"""name

Revision ID: 17ca2422ca29
Revises: 5e48fb9d97cc
Create Date: 2024-04-15 22:59:18.821218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ca2422ca29'
down_revision: Union[str, None] = '5e48fb9d97cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_constraint('roles_name2_key', 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_column('roles', 'name2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name2', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint('roles_name2_key', 'roles', ['name2'])
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###
