"""rename1

Revision ID: 52f8fcb55b4d
Revises: 63565fe3f2e4
Create Date: 2024-04-15 22:56:03.471615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f8fcb55b4d'
down_revision: Union[str, None] = '63565fe3f2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name1', sa.String(length=255), nullable=False))
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['name1'])
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_column('roles', 'name1')
    # ### end Alembic commands ###
